import { HomeLocationData } from "./../api/locationAPI";
export type RootStackParamList = {
  Login: undefined;
  EmailLogin: undefined;
  Register: {email: string; password:string };
  PhoneLogin: undefined;
  Home: undefined;
  VerifyCode: { email: string , password?: string};
  Map: {homeLocation: HomeLocationData, currentLocation: HomeLocationData};
  HomeLocationSetup: { mode?: "goHome" | "return" } | undefined;
  Profile: undefined;
  Settings: undefined;
  DriverFound: { ride?: any; driver?: any; rideId?: string } | undefined;
  FindingDriver: { rideId?: any; drivers?: any[]; pickup?: { lat: number; lng: number }; vehicleTypeId?: string } | undefined;
  DriverNavigate: { rideId: string } | undefined;
  DriverDashboard: undefined;
  RideRequests: undefined;
  DriverDrawer: undefined;
  Splash: undefined;
};
