// data/mockUsers.ts
import { User } from "../types/user";

export const mockUsers: User[] = [
  {
    id: "u001",
    firstName: "Anna",
    lastName: "Nguyen",
    phone: "0987654321",
    email: "anna.nguyen@example.com",
    role: "customer",
    gender: "female",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    dob: "1995-05-22",
  },
  {
    id: "u002",
    firstName: "Cameron",
    lastName: "Williamson",
    phone: "0912 345 678",
    email: "cameron.williamson@example.com",
    role: "driver",
    gender: "male",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    dob: "1990-08-15",
  },
  {
    id: "u003",
    firstName: "Sophia",
    lastName: "Tran",
    phone: "0911 222 333",
    email: "sophia.tran@example.com",
    role: "customer",
    gender: "female",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    dob: "1997-11-02",
  },
  {
    id: "u004",
    firstName: "David",
    lastName: "Pham",
    phone: "0934 555 111",
    email: "david.pham@example.com",
    role: "driver",
    gender: "male",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
    dob: "1988-03-09",
  },
  {
    id: "u005",
    firstName: "Mia",
    lastName: "Le",
    phone: "0920 888 777",
    email: "mia.le@example.com",
    role: "customer",
    gender: "female",
    avatar: "https://randomuser.me/api/portraits/women/23.jpg",
    dob: "2000-01-20",
  },
  {
    id: "u006",
    firstName: "Admin",
    lastName: "System",
    phone: "0900 000 000",
    email: "admin@example.com",
    role: "admin",
    gender: "other",
    avatar: "https://randomuser.me/api/portraits/lego/1.jpg",
    dob: "1985-06-30",
  },
];
